#!/bin/sh
GNUCAP=${GNUCAP-gnucap}
if [ $# -eq 0 ] ; then
    echo "usage: ./test gnucap-verilog \"testcases\" targetdir refdir"
    echo "usual testcases is \"\", usual refdir is =="
    echo "example: ./test gnucap-mg-vams \"\" myversion =="
    exit 1
else
    \mkdir $3 2> /dev/null || echo re-using directory $3
    \rm -f $3/$2.diffs
    ls $2*.sh 2>/dev/null >/dev/null && \
    for ii in $2*.sh
    do
	echo $ii
	echo $ii >>$3/$2.diffs
	./$ii $1 >$3/$ii.out
	diff -u $4/$ii.out $3/$ii.out >>$3/$2.diffs || echo "**** $ii fails ****"
    done
    ls $2*.vapp 2>/dev/null >/dev/null && \
    for ii in $2*.vapp
    do
	echo $ii
	echo $ii >>$3/$2.diffs
	$1 -I.. -D__VAMS_GNUCAP --pp $ii >$3/$ii.out
	diff -u $4/$ii.out $3/$ii.out >>$3/$2.diffs || echo "**** $ii fails ****"
    done
    ls $2*.vams 2>/dev/null >/dev/null && \
    for ii in $2*.vams
    do
	echo $ii
	echo $ii >>$3/$2.diffs
	$1 -I .. --dump $ii >$3/$ii.out
	diff -u $4/$ii.out $3/$ii.out >>$3/$2.diffs || echo "**** $ii fails ****"
    done
    ls $2*.gc 2>/dev/null >/dev/null && \
    for ii in $2*.gc
    do
	echo $ii
	echo $ii >>$3/$2.diffs
	${GNUCAP} -a ../lang_verilog.so $ii |tail -n +30 |grep -v ^make \
	    | grep -v '^stashing\ as' | grep -v 'already\ installed' >$3/$ii.out
	diff -u $4/$ii.out $3/$ii.out >>$3/$2.diffs || echo "**** $ii fails ****"
    done
    echo done with $1 $2 >>$3/$2.diffs
    echo done with $1 $2
    exit 0
fi
# vim:sw=4:ts=8:noet
