/*                          -*- C++ -*-
 * Copyright (C) 2001 Albert Davis
 *               2022-26 Felix Salfelder
 *
 * This file is part of "Gnucap", the Gnu Circuit Analysis Package
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 3, or (at your option)
 * any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA
 * 02110-1301, USA.
 */

#include <md.h>
#include "mg_out.h"
#include "mg_in.h"
#include "mg_options.h"
#include "mg_discipline.h"
#include "mg_.h" // TODO
/*--------------------------------------------------------------------------*/
static void make_header(std::ostream& o, const File& in,
			const std::string& /*dump_name*/)
{
  o << in.head() << 
    "/* This file is automatically generated. DO NOT EDIT */\n"
    "/*--------------------------------------"
    "------------------------------------*/\n";
  o <<
    "#include <globals.h>\n"
    "#include <u_nodemap.h>\n" // if submodules are used anywhere
    "#include <e_compon.h>\n"
    "#include <e_subckt.h>\n"
    "#include <e_node.h>\n"
    "#include <e_elemnt.h>\n"
    "#include <e_storag.h>\n"
    "#include <e_hsparam.h>\n"
    "// #include <e_paramlist.h>\n"
    "#include <m_random.h>\n";
#ifdef DEPEND
  // nothing. just compute deps.
#elif defined(RETEST)
  o <<
    "#include <m_va.h>\n"
    "#include <e_va.h>\n";
#else
  o <<
#include "m_va.raw"
     ;
  o <<
#include "e_va.raw"
     ;
#endif
  if(options().gen_discipline()){
    o << "#include <e_node_type.h>\n";
  }else{ untested();
  }
  o <<
    "#include <u_limit.h>\n"
    "#include <bitset>\n"
    "#include <typeindex>\n"
    "/*--------------------------------------"
    "------------------------------------*/\n";

  // this warning does not help.
  o << "#pragma GCC diagnostic ignored \"-Wunused-local-typedefs\"\n";
  // Wunused is adding noise in nested temporaries. None of them is
  // actually wrong.
  o << "#pragma GCC diagnostic ignored \"-Wshadow\"\n";
  o <<
    "const double NA(NOT_INPUT);\n"
    "const double INF(BIGBIG);\n"
    "/*--------------------------------------"
    "------------------------------------*/\n";
  o << "namespace { // head\n"
    "/*--------------------------------------"
    "------------------------------------*/\n";
}
/*--------------------------------------------------------------------------*/
static void make_tail(std::ostream& o, const File&)
{
  o << // in.cc_direct() <<
    "/*--------------------------------------"
    "------------------------------------*/\n"
    "} // tail\n"
    "/*--------------------------------------"
    "------------------------------------*/\n";
}
/*--------------------------------------------------------------------------*/
void make_continuous_discipline(std::ostream& o, Discipline const& d);
void make_discrete_discipline(std::ostream& o, Discipline const& d);
/*--------------------------------------------------------------------------*/
static void make_common_nature(std::ostream& o, const File& f)
{
  for(auto i : f.nature_list()) {
    o << "class NATURE_" << i->identifier() << " : public NATURE {\n";
    o__ "double abstol()const override {return "<<i->abstol()<<";}\n";
    o << "}_N_"<<i->identifier()<<";\n";
  }
  o << "/*--------------------------------------"
       "------------------------------------*/\n";
}
/*--------------------------------------------------------------------------*/
static void make_cc_discipline(std::ostream& o, File const& f)
{
  o << "namespace {\n";
  for(auto d : f.discipline_list()) {
    assert(d);
    if(d->is_discrete()) {
      make_discrete_discipline(o, *d);
    }else{
      make_continuous_discipline(o, *d);
    }
  }
  o << "}\n";
  o << "/*--------------------------------------"
       "------------------------------------*/\n";
}
/*--------------------------------------------------------------------------*/
void make_cc(std::ostream& out, const File& in)
{
  indent x; // HACK
  int num = 0;
  make_header(out, in, "dumpname");
  make_common_nature(out, in);

  if(options().gen_discipline()){
    make_cc_discipline(out, in);
  }else{ untested();
  }

  if(options().gen_paramset()){
    for (Paramset_List::const_iterator
	 m = in.paramset_list().begin();
	 m != in.paramset_list().end();
	 ++m) {
      out << "namespace n" << std::to_string(num) << "{\n";
      make_cc_module(out, **m);
      out << "} // n" << std::to_string(num) << "\n"
    "/*--------------------------------------"
    "------------------------------------*/\n";
      ++num;
    }
  }else{ untested();
  }

  if(options().gen_module()){
    for (Module_List::const_iterator
	 m = in.module_list().begin();
	 m != in.module_list().end();
	 ++m) {
      out << "namespace n" << std::to_string(num) << "{\n";
      make_cc_module(out, **m);
      out << "} // n" << std::to_string(num) << "\n"
    "/*--------------------------------------"
    "------------------------------------*/\n";
      ++num;
    }
  }else{
  }

  for (auto p : in.primitive_list()) {
    out << "namespace n" << std::to_string(num) << "{\n";
    make_cc_primitive(out, *p);
    out << "} // n" << std::to_string(num) << "\n"
      "/*--------------------------------------"
      "------------------------------------*/\n";
    ++num;
  }

  make_tail(out, in);
}
/*--------------------------------------------------------------------------*/
/*--------------------------------------------------------------------------*/
// vim:ts=8:sw=2:noet
